-- MySQL Script generated by MySQL Workbench
-- Mon Sep 24 14:42:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbinventario3m
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbinventario3m
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbinventario3m` DEFAULT CHARACTER SET utf8 ;
USE `dbinventario3m` ;

-- -----------------------------------------------------
-- Table `dbinventario3m`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(55) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `telefono` INT(11) NULL,
  `email` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinventario3m`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinventario3m`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `stock` VARCHAR(45) NULL,
  `descripcion` VARCHAR(150) NULL,
  `imagen` VARCHAR(50) NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbinventario3m`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinventario3m`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`inventario` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `cant_producto_ingreso` VARCHAR(45) NOT NULL,
  `cant_producto_vendido` VARCHAR(45) NOT NULL,
  `cant_producto_restante` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(11,3) NOT NULL,
  PRIMARY KEY (`idinventario`),
  INDEX `idproducto_idx` (`idproducto` ASC),
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `dbinventario3m`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinventario3m`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idinventario` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `valor_total` DECIMAL(11,3) NOT NULL,
  `estado_venta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_venta_cliente_idx` (`idcliente` ASC),
  INDEX `fk_venta_inventario_idx` (`idinventario` ASC),
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `dbinventario3m`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_inventario`
    FOREIGN KEY (`idinventario`)
    REFERENCES `dbinventario3m`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinventario3m`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`detalle_venta` (
  `iddetalle_factura` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idventa` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(11,3) NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `descuento` DECIMAL(11,3) NOT NULL,
  PRIMARY KEY (`iddetalle_factura`),
  INDEX `fk_detalle_venta_venta_idx` (`idventa` ASC),
  INDEX `fk_detalle_venta_producto_idx` (`idproducto` ASC),
  CONSTRAINT `fk_detalle_venta_venta`
    FOREIGN KEY (`idventa`)
    REFERENCES `dbinventario3m`.`venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `dbinventario3m`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinventario3m`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `idinventario` INT NOT NULL,
  `comprobante` VARCHAR(45) NOT NULL,
  `num_comprobante` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_ingreso_inventario_idx` (`idinventario` ASC),
  CONSTRAINT `fk_ingreso_inventario`
    FOREIGN KEY (`idinventario`)
    REFERENCES `dbinventario3m`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinventario3m`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinventario3m`.`detalle_ingreso` (
  `iddetalle_ingreso` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idingreso` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `precio_compra` VARCHAR(45) NOT NULL,
  `precion_venta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddetalle_ingreso`),
  INDEX `fk_detalle_ingreso_ingreso_idx` (`idingreso` ASC),
  INDEX `fk_detalle_ingreso_producto_idx` (`idproducto` ASC),
  CONSTRAINT `fk_detalle_ingreso_ingreso`
    FOREIGN KEY (`idingreso`)
    REFERENCES `dbinventario3m`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ingreso_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `dbinventario3m`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
